name: Deploy Docker App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to EC2 using SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 23.20.236.45
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          whoami
          hostname
          ls -la /home/ubuntu
          cd /home/ubuntu/Python_Protfolio_Website   # or wherever your repo is cloned
          git pull origin main
          docker build -t myapp .
          docker stop ajmdrstalha-portfolio || true
          docker rm ajmdrstalha-portfolio || true
          docker run -d -p 9001:8501 --name ajmdrstalha-portfolio myapp
