name: Deploy py_portfolio With CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to EC2 using SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "SSH connection successful!"
          whoami
          hostname
          ls -la /home/ubuntu
          cd /home/ubuntu/Python_Protfolio_Website   # wherever your repo is cloned
          git pull origin main
          docker rmi py_portfolio:v1.0.0 || true
          docker build -t py_portfolio:v1.0.0 .
          docker stop ajmdrstalha-portfolio || true
          docker rm ajmdrstalha-portfolio || true
          docker run -d -p 9001:8501 --name ajmdrstalha-portfolio py_portfolio:v1.0.0
